package com.sample.rules

import com.sample.WindowState;
import com.sample.DroolsTest;

declare Question
	questionText: String
	answer: String
end

rule "answer_handler"
when
	$windowState : WindowState(getAnswer() != "");
	$question : Question(answer==null);
then
	modify($question) {
        setAnswer($windowState.getAnswer())
    	}
  	$windowState.setAnswer("");
    update($question);
    update($windowState);
end

rule "Init"
	when
	then
		System.out.println("init");
		insert(new WindowState("What type of game are you looking for?", new String[]{"I want a wargame", "A strategy game"}));
    	insert(new Question("What type of game are you looking for?", null));
end



rule "2-wargame"
	when
		$question: Question(questionText == "What type of game are you looking for?", answer == "I want a wargame");
		$windowState : WindowState(getAnswer() == "");
	then
		System.out.println("2-wargame");
		insert(new Question("For how many players?", null));
		$windowState.setText("For how many players?");
		$windowState.setPossibleAnswers(new String[]{"2 or more", "Just me"});
    	update($windowState);
end

rule "3-wargame"
	when
		$question: Question(questionText == "For how many players?", answer == "Just me");
		$windowState : WindowState(getAnswer() == "");
	then
		System.out.println("3-wargame-recommendation");
		$windowState.setText("Recommendation: <br> 1. Field Commander Series <br> 2. Thunderbolt: Apache Leader <br> 3. Space Infantry");
		$windowState.setPossibleAnswers(null);
    	update($windowState);
end





